### ISSUE TITLE
Fix build process

### ISSUE THREAD

**Issue by talexand** [teampizza/backpack#31]
Current gulp scripts fail under node 12 and npm 2.

This needs to be fixed before anything else can go on.

**Comment by talexand** [comment]
bug 1: build in socketwatcher:

```npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/home/sobakasu/.nvm-fish/v0.12.0/bin/node" "/home/sobakasu/.nvm-fish/v0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls socketwatcher```

**Comment by epilande** [comment]
bug 2: nodemon TypeError: Cannot call method 'map' of undefined

```
/Users/ERP/Projects/backpack/node_modules/nodemon/lib/nodemon.js:138
    utils.log.detail('ignoring: ' + config.options.monitor.map(function (rule)
                                                           ^
TypeError: Cannot call method 'map' of undefined
    at /Users/ERP/Projects/backpack/node_modules/nodemon/lib/nodemon.js:138:60
    at /Users/ERP/Projects/backpack/node_modules/nodemon/lib/config/index.js:79:7
    at ready (/Users/ERP/Projects/backpack/node_modules/nodemon/lib/config/checkWatchSupport.js:28:7)
    at /Users/ERP/Projects/backpack/node_modules/nodemon/lib/config/checkWatchSupport.js:61:9
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by talexand** [comment]
Reported the first bug upstream at https://github.com/btrask/node-socketwatcher/issues/7

**Comment by talexand** [comment]
@epilande what version of node are you running for that map error?

**Comment by talexand** [comment]
@epilande also, check the gulp tasks containing nodemon individually and paste the errors you get; thanks.

**Comment by Gusgus01** [comment]
I have received both those errors while trying to get backpack running. I can add that the map error is only most of the time for me. If you try enough eventually it will launch which is even more peculiar.

**Comment by epilande** [comment]
@talexand my node version is `v0.12.3` & npm `2.9.1`

I'm still getting that map error when running `gulp`.

When I run `gulp parser` & `gulp modeler`, I get the same error for both commands:
```
Error: `libsass` bindings not found in /Users/ERP/Projects/backpack/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/Users/ERP/Projects/backpack/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> (/Users/ERP/Projects/backpack/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ERP/Projects/backpack/node_modules/gulp-sass/index.js:157:21)
    at Module._compile (module.js:456:26)
```

Also tried running without gulp.. `nodemon backend/parser/pcap_parser.js` & `nodemon backend/modeler/model_master.js`, I get this error for both:
```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/ERP/Projects/backpack/node_modules/mongojs/node_modules/mongodb/node_modules/bson/build/Release/bson.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/ERP/Projects/backpack/node_modules/mongojs/node_modules/mongodb/node_modules/bson/build/Release/bson.node
  Expected in: dynamic lookup
```

**Comment by talexand** [comment]
Next time we meet up, I'm going to try rewriting this as a collection of npm scripts. I've heard some valid criticism of gulp, so if we can cut out that middleman, it's worth a shot.

**Comment by talexand** [comment]
Followup: this does not seem to be a gulp problem. The node-sass problem involves a version mismatch and a recurring bug (see https://github.com/sass/node-sass/issues/653). A workaround is to use node version v0.10.38 until the situation stabilizes. Be sure to delete `node_modules/` and re-run `npm install`.

**Comment by epilande** [comment]
See https://github.com/JacksonGariety/gulp-nodemon/issues/6 for nodemon error `TypeError: Cannot call method 'map' of undefined` when running default task `$ gulp`. To get up and running start parser (`$ gulp parser`) & modeler (`$ gulp modeler`) task individually

**Comment by ghost** [comment]
I'll fix this by changing our build process to npm tasks.

**Comment by talexand** [comment]
Note that if nvm is running in a different shell than the one you have configured, the permissions setting will not be able to find that executable since the environment vars are different (`$NVM_BIN` will not exist, for example). This happens if you run `fish` and is something I need to figure out.

**Comment by ghost** [comment]
@epilande can you add a sass script to the npm scripts? Thanks.
